sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LDM-622.pdf --upload --lsstdoc LDM-622.tex --env=travis --ltd-product ldm-622"
env:
  global:
    # LSST the Docs credentials
    - secure: "RUuGxyrR/SLZoxgljFhiDsvG7Uxq8du9d2i2HAEEYnaf2uhfpuBDOPCQOsYbfu5kJJ/PjOtAaVloIsGbdFY9tlCHm8qPBC1KSk4SVp2bqWndof2hYTPDzwRkOVw7WrL+KCfliS6iXiQIngGfbkKGgdyfAyD4vxsjgn161c1lbj30Yyd8w+ENg10jKVN57seSENmV8YO1LVBafG+dc33CFSkfGClFwIbkj+UV+7HjwtRxE3cRggSzQ2GAjPH6TCtGjqc2RaKaZXRAMDR8q+niSUO0dRZUk8qf9sc+gblXeYWkQCUTFuiEuswANtIzEUHdyXXGuMQwwmYmUg5lhGIP8I3iptCJyJk8/6NuhjI1QnpGILTZB5Ft3fjQvhm9DI9lZITgbTnLNlo8c8PaOXhNoJR7JZP/RlSCDMwaUIMLiAyoWcTxfxWJyvqs5M7TQBkH18ZkqTPU4CqRgaiJz3MA04WtwVO0z3JUllo/gywkhgswZ/ziT3+VFQZdmlP7yfGNEJMTO4Ej/188nPIkepLxWhov8AimzNmnLWm2vVpv9tZHT+32LLvfm2fT/8zInFPeORo0YOKQwLkz0HcbtGV3WHk6hrSV2KFhK1TAfJJF/k8eAZQXHFMrWKstMtMFdsCnSMJPkrgQQ3fcuPjuIKs60kAhpCpcfybvQFbWzPqCDpY="
    - secure: "exwA4RHrcSZJKN8rOK8YGc2DS7Ofjf5dLio+0QiAAtS6Mb71BKma7HA75oLLafI7Ymm1qJrUMEfDIAaeCYNqDgovfKeuBiZz56OYO7e1LeF/ea6X0/dPW5PCADelXJgp45g5CKLDqw1edR4sC+1glDHVeAsDJpn2Q6sMj926t9pVKtc9rojgRcjFSlHc8NQ3hYa9StCMaFtnh5J+Zi5X1e1W0JZhODORUw6p0v+R8FCNO1VyRsQCQxYbOR3ow2olk2klBwSS2Z8sclJ2H71ZZd57Au2DRTkMq1Cb2uh+vzcM89OEWg0N/d2oFe17JXPz+hmEaZNTWF9i+6vTRXbUejDyyDG5nu6VLYAa1ZroEuqLZC+zyyA743lseN7W3GjrUb3KOBZmAXkvNJwcLCpk5rxrgohJ3huXx/uBUgOVhb5ZKOmC+yTM111CgcpyR0ak9odz2MxZqizdExHJApCONS1iSBVaITcEGeQQUri2P9YE3+VI7GtvMyxlQzPs0O4mDDGcX5Iv0FTjr9vFhlElZ8JzKW6xONSYmybr5+zM+51rmGJgOU0tCh4+sMDIF+FnStLPx+QkfqiSsdOiNfIYFVgFxJFxsWw4lSPUzSgfnYFY4J8s/BMjCJLC0UKJ2t95nnMejUAtKNBXb0qULijC1h2QTSN2zR82p5chEtMe1oU="
